Created a new class CommandGenerator in command_generator.py
GDGVizag/bevy-invitation-automation pull request #7
Opened 2023-10-24 14:28 UTC by Yaswanth14

Worked on issue #4  
Created a new class CommandGenerator in command_generator.py and moved to generate_* functions from main to the new class

2023-11-09 05:07 UTC, sampathbalivada commented
Hi @Yaswanth14, could you please share a screenshot of successful run of the script?

2023-11-09 06:47 UTC, Yaswanth14 commented
Hey @sampathbalivada, I observed few errors while running the script which are resolved now

### Screenshot of successful run of script:

![image](https://github.com/GDGVizag/bevy-invitation-automation/assets/73766693/bb8f578d-2829-4685-8ad6-4d39f6a16e3f)

### Details of the updated commit:

- Creating an instance for `get_command_template` as `command_template` in command_generator.py
- Redefining the instaces created for `generate_*` methods

2023-11-10 16:53 UTC, sampathbalivada requested changes
Please modify as specified.

2023-11-10 16:53 UTC, sampathbalivada commented on src/command_generator.py
> +    def add_command(self, command):
I don't see where we are using the method. Remove this method.

2023-11-10 16:53 UTC, sampathbalivada commented on src/main.py
> +        # Create instances of the generate_* methods
Instead of copying the method reference, modify the code in other places to use the `self.command_generator` instance.

2023-11-10 17:50 UTC, Yaswanth14 commented
> Please modify as specified.

Modified the code, kindly review the changes made

2023-11-13 19:41 UTC, sampathbalivada approved these changes
LGTM. Please share a screenshot of the sample run so that I can merge the PR.

2023-11-14 16:03 UTC, Yaswanth14 commented
> LGTM. Please share a screenshot of the sample run so that I can merge the PR.

### Here's the screenshot of sample run
![image](https://github.com/GDGVizag/bevy-invitation-automation/assets/73766693/78d231ed-6b04-4175-8327-dfe0710a74c8)

2024-10-23 06:16 UTC, closed without merging